### ISSUE TITLE
BuildTasks::GitBuildpackage broken on Ubuntu 16.04 & Debian sid

### ISSUE THREAD

**Issue by hrak** [Jimdo/buildtasks#2]
Hi,

BuildTasks::GitBuildpackage currently does not work on Ubuntu 16.04 and Debian Sid, because the `git-buildpackage` binary is no longer included in the git-buildpackage package. The command should be `gbp buildpackage` on these newer distros (which AFAICS is also backwards compatible with the package on Ubuntu 14.04 & Debian Jessie)

See http://packages.ubuntu.com/trusty/all/git-buildpackage/filelist vs http://packages.ubuntu.com/xenial/all/git-buildpackage/filelist
https://packages.debian.org/nl/jessie/all/git-buildpackage/filelist vs https://packages.debian.org/nl/sid/all/git-buildpackage/filelist

**Comment by mlafeldt** [comment]
Hey @hrak,

Thanks for reporting.

I hope that 3c308dab255ec93897c7147d79cc7f24dab9c4fb fixes the issue for you. Please give version 0.0.6 of the gem a try and report back.

**Comment by hrak** [comment]
@mlafeldt Its working now, thanks for the quick update!

**Comment by mlafeldt** [comment]
Awesome! 🎉 

I'd love to hear more about your use case. At Jimdo, we're mainly using Docker containers these days, and rarely need to (re)build Debian packages. In any case, I'm glad that the library still provides value to others.

**Comment by hrak** [comment]
I was looking for a nice and clean way to do repeatable builds of deb packages, and found [this article](https://blog.codeship.com/using-docker-build-debian-packages/) that uses buildtasks and fpm to compile packages inside a container. At LeaseWeb we build packages for OpenResty and some Prometheus exporters, and this will help to automate the package building process.

**Comment by mlafeldt** [comment]
Very cool! Thanks for your feedback.
